# Generated by Django 3.1.5 on 2021-02-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desdcription',
            new_name='description',
        ),
    ]
